// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIETIDsJHutcHwM9lG-v4eeJczuMahOQ',
    appId: '1:570470940714:android:61051086e6da4189f80353',
    messagingSenderId: '570470940714',
    projectId: 'fluttercourse-9f412',
    storageBucket: 'fluttercourse-9f412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVWNJrtCIREO7CTK0RGgZCXj0UhKIGNvs',
    appId: '1:570470940714:ios:24949e436df3507af80353',
    messagingSenderId: '570470940714',
    projectId: 'fluttercourse-9f412',
    storageBucket: 'fluttercourse-9f412.firebasestorage.app',
    androidClientId: '570470940714-mpsp1o4npul6fu85asjmb6jfhvhkk2j5.apps.googleusercontent.com',
    iosClientId: '570470940714-52eo28begboa2kt3c6t8hjr4n3cd8v6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteAppDepi',
  );
}
